{{- if .Values.route.slack.enabled }}
{{- if .Values.secret.openwhisk.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.openwhisk.secret_name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
type: Opaque
data:
  url: {{ .Values.secret.openwhisk.url }}
  id: {{ .Values.secret.openwhisk.id }}
  pwd: {{ .Values.secret.openwhisk.pwd }}
{{- end }}
{{- end }}
